version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  nginx:
    image: nginx:stable-alpine
    ports:
      - '7070:7070'
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      grafana:
        condition: service_healthy
    restart: always

  grafana:
    image: grafana/otel-lgtm
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    networks:
      - backend

  db:
    image: postgres:16.3
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge