version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  jaeger:
    image: jaegertracing/all-in-one:1.58.0
    ports:
      - '16686:16686'
      - '4318:4318'
    networks:
      - backend
    command: [
      '--query.max-clock-skew-adjustment=1s'
    ]

  db:
    image: postgres:16.3
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge